- name: Setup Homelab
  hosts: homelab
  roles:
    - role: common

- name: Start VMs
  hosts: homelab
  roles:
    - role: create_vm
      vm_name: ubuntu-test-1
    - role: create_vm
      vm_name: ubuntu-test-2
  tags:
    - create

- name: Destroy all VMs
  hosts: homelab
  roles:
    - role: destroy_vms
  tags:
    - never
    - destroy

- name: Install Kubernetes
  hosts: vms
  roles:
    - role: kubernetes_install
  tags:
    - never
    - k8s
