- name: Setup Homelab
  hosts: homelab
  roles:
    - role: install_common
    - role: install_packer
  tags:
    - install

- name: Start VMs
  hosts: homelab
  roles:
    - role: create_vm
      vm_name: control-plane-1
      vcpus: 3
      memory_mb: 4096
      disk_size: 10G

    - role: create_vm
      vm_name: worker-1
      vcpus: 3
      memory_mb: 4096
      disk_size: 10G
  tags:
    - create

- name: NAT VMs
  hosts: homelab
  roles:
    - role: nat_vms
  tags:
    - nat

- name: Install Kubernetes
  hosts: vms
  roles:
    - role: install_kubernetes
  tags:
    - never
    - k8s

- name: Destroy all VMs
  hosts: homelab
  roles:
    - role: destroy_vms
  tags:
    - never
    - destroy
