- name: Setup Homelab
  hosts: homelab
  roles:
    - role: common

- name: Start VMs
  hosts: homelab
  roles:
    - role: create_vm
  tags:
    - create

- name: Destroy all VMs
  hosts: homelab
  roles:
    - role: destroy_vms
  tags:
    - never
    - destroy
