- name: Setup Homelab
  hosts: homelab
  roles:
    - role: install_common
    - role: install_packer
    - role: convert_to_server
    - role: setup_vm_networking
  tags:
    - install

- name: Virtualize GPU
  hosts: homelab
  roles:
    - role: virtualize_gpu
  tags:
    - virtualize-gpu

- name: Start VMs
  hosts: homelab
  roles:
    - role: create_vm
      vm_name: control-plane-1
      vcpus: 3
      memory_mb: 4096
      disk_size: 10G
      network_interface: bridge

    - role: create_vm
      vm_name: worker-1
      vcpus: 2
      memory_mb: 2048
      disk_size: 10G
      network_interface: bridge

    - role: create_vm
      vm_name: worker-2
      vcpus: 2
      memory_mb: 2048
      disk_size: 10G
      network_interface: bridge
  tags:
    - create

- name: get VM IPs
  hosts: homelab
  roles:
    - role: get_vm_ip
  tags:
    - ip
    - never

- name: Install Kubernetes
  become: true
  hosts: vms
  roles:
    - role: install_kubernetes
  tags:
    - never
    - k8s

- name: Run Kubernetes
  hosts: localhost
  roles:
    - role: run_kubernetes
  tags:
    - never
    - k8s

- name: Destroy all VMs
  hosts: homelab
  roles:
    - role: destroy_vms
  tags:
    - never
    - destroy
